### ISSUE TITLE
IList<T> as an input type

### ISSUE THREAD

**Issue by snnz** [eocron/ORegex#6]
Consider changing ORegex functions' input sequence type from T[] to IList&lt;T>. This way, all T[], List&lt;T>, ArraySegment&lt;T>, etc. would have been supported. ArraySegment is particularly useful for various recursive matches without memory overheads.

**Comment by eocron** [comment]
Hello, thank you for your proposal. I changed signature to support IList<T>, so now you can use everything you see fit in your application. Nuget package will be available later, for now you can pull master branch and compile it yourself.

**Comment by snnz** [comment]
Thanks!
